### ISSUE TITLE
Enhance branch protection

### ISSUE THREAD

**Issue by dhiller** [kubevirt/project-infra#212]
As of #209 the branch protection has been set up per repo. This should be enhanced and simplified, as in: enable it for all branches org wide,i.e.

```
branch-protection:
  protect: true
  required_status_checks:
    contexts:
    - dco
    - continuous-integration/travis-ci/pr
    - coverage/coveralls
```

**BUT** when testing locally with phaino there were couple of problems:
- the requests timed out (possibly due to rate limits or the http://ghproxy configured which obviously doesn't work locally)
- there were 404s (possibly related to bad access rights)
- some seemed to not be able to find current (non-existing) branch protection rules, resulting in erroring with 404, might be worth opening an issue against test-infra
