### ISSUE TITLE
Periodic job for CDI `make rpm-deps`

### ISSUE THREAD

**Issue by cfilleke** [kubevirt/project-infra#3595]
**Is your feature request related to a problem? Please describe**:
`make rpm-deps` is not a periodic job to be run for CDI as it is for kubevirt

**Describe the solution you'd like**:
In kubevirt there is a periodic job configured for `make rpm-deps` in ` /project-infra/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml` that updates the rpm dependencies weekly and reads: 
```
- annotations:
    testgrid-create-test-group: "false"
  cluster: kubevirt-prow-control-plane
...
      - ../project-infra/hack/git-pr.sh -c "cd ../kubevirt && make rpm-deps" -b bump-rpm-dependencies

```

There is no automation for periodically running `make rpm-deps` for CDI, however. 

The proposal here is to add a prow job to `project-infra/github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml` that executes `make rpm-deps` and opens the PR to update the `containerized-data-importer/WORKSPACE` and `containerized-data-importer/rpm/BUILD.bazel` files in main. @awels has suggested we make this a monthly periodic job. 

**Describe alternatives you've considered**:
The alternative to running this out of a prow job is to run `make rpm-deps` manually for CDI and then create a PR that updates `containerized-data-importer/WORKSPACE` and `containerized-data-importer/rpm/BUILD.bazel`  manually.  This is how it is done now. 

**Additional context**:
It's not clear what vetting of the dependent rpms is being conducted, e.g. for CVE issues and breaking functional changes. These things are encountered _ad hoc_. 

The latest manual run of `make rpm-deps` PR is here: https://github.com/kubevirt/containerized-data-importer/pull/3405

Issue initially raised in: https://groups.google.com/g/kubevirt-dev/c/pe__J0KT-zk/m/tx8-k54SCAAJ
